### ISSUE TITLE
Issue #1 - User can add an event to the planner.

### ISSUE THREAD

**Issue by JRodriguez-Luna** [JRodriguez-Luna/week-planner#1]
![user-can-add-events](https://github.com/user-attachments/assets/d8814859-dad0-4002-95b7-ff73476c2532)

## ✅ Task List

- [x] Create the remaining HTML.
  - [x] Create a button name `Add New Events` and give options to the user of what day of the week would they like:
    - [x] Monday, Tuesday, etc. 
- [x] Create a table like and make sure the head of the table carry its own individual heading:
  - [x] Time
  - [x] Event
  - [x] Actions
- [x] Create a modal to select the following:
  - [x] Time of Event
    - [x] Default option select `Choose a Time`.
  - [x] Day of Week
    - [x] Default option select `Choose a Day`.
    - [ ] default to the original Day of Week (optional).
  - [x] Event Info
    - [x] Allow the user to add text.
  - [ ] Create buttons named `Cancel` and `Confirm`.
- [ ] Create an even listener for:
  - [ ] `Add New Events` button
  - [ ] the modal
    - [ ] `Cancel` and `Confirm` button
- [ ] Make sure the users info is displayed onto the table.
- [ ] Create or add any additional things needed to complete the the issue.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
